engines:
  rubocop:
    enabled: true
    checks:
    Rubocop/Metrics/ClassLength:
      enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
exclude_paths:
- react/**/*
- app/assets/javascripts/application.js
- app/assets/javascripts/cable.js
- db/**/*
